name: Flake8

on:
  push:
    branches: [ master ]
    paths: [ '**.py' ]
  pull_request:
    branches: [ master ]
    paths: [ '**.py' ]

jobs:
  flake8_lint:
    name: Lint with Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt
      - name: Lint with flake8
        run: flake8 . --count --statistics --max-line-length=120